logging:
    logfiles:
        api: "~/cassabon/api.log"
        carbon: "~/cassabon/carbon.log"
        system: "~/cassabon/system.log"
    loglevel: "info"
cassandra:
    hosts:
        - "127.0.0.1"
        - "localhost"
    port: 9000
api:
    address: "0.0.0.0"
    port: 8080
elasticsearch:
    host: "127.0.0.1"
    port: 9200
carbon:
    address: "0.0.0.0"
    port: 2003
    protocol: "udp"
statsd:
    host: "localhost"
    port: 8125
rollups:
    default:
        - "10s:6h"
        - "1m:1d"
