logging:
    logdir: ""
    loglevel: "info"
cassandra:
    hosts:
        - "127.0.0.1"
        - "localhost"
    port: 9000
api:
    address: "0.0.0.0"
    port: 8080
redis:
    index:
        sentinel: false
        addr:
            - "127.0.0.1:6379"
        db: 0
    queue:
        sentinel: true
        addr:
            - "127.0.0.1:26379"
        db: 1
carbon:
    address: "0.0.0.0"
    port: 2003
    protocol: "udp"
statsd:
    host: "localhost"
    port: 8125
rollups:
    default:
        - "10s:6h"
        - "1m:1d"
