logging:
    logdir: ""
    loglevel: "info"
statsd:
    host: "127.0.0.1"
    port: 8125
    events:
        receiveok:
            key: "carbon.received.success"
            samplerate: 1.0
        receivefail:
            key: "carbon.received.failure"
            samplerate: 1.0
channels:
    datastorechanlen: 10
    datafetchchanlen: 10
    indexstorechanlen: 10
    indexfetchchanlen: 10
carbon:
    listen: "127.0.0.1:2003"
    protocol: "tcp"
    parameters:
        tcptimeout: 5
        udptimeout: 5
    peers:
        - "127.0.0.1:2003"
api:
    listen: "127.0.0.1:8080"
    healthcheckfile: "config/healthcheckfile"
cassandra:
    hosts:
        - "127.0.0.1"
    port: 9042
    keyspace: "cassabon_dev"
    strategy: "SimpleStrategy"
    createopts: "'replication_factor':1"
redis:
    addr:
        - "127.0.0.1:6379"
    db: 5
    pwd: ""
    pathkeyname: "cassabon_dev"
    sentinel: false
    master: ""
rollups:
  ^foo.*:
    retention:
      - 6s:30m
      - 1m:30d
      - 1h:1y
    aggregation: sum
  ^foo2.*:
    retention:
      - 15ms:30m
      - 7s:30m
      - 1m:30d
      - 1h:1y
    aggregation: average
  ^foo1.*:
    retention:
      - 1m:30d
      - 1h:1y
      - 6s:30m
    aggregation: sum
  ^bar.*:
    retention:
      - 10s:1h
      - 1m:30d
    aggregation: max
  ^bar.baz.*:
    retention:
      - 10s:1h
      - 1m:30d
    aggregation: min
  ^bar.quux.*:
    retention:
      - 10s:1h
      - 1m:30d
    aggregation: max
  ^bar.zoom1.*:
    retention:
      - 10s:1h
    aggregation: garbage
  ^bar.zoom2.*:
    retention:
      - 10q:1h
    aggregation: sum
  ^bar.(zoom2.*:
    retention:
      - 10q:1h
    aggregation: sum
  default:
    retention:
      - 15s:1d
      - 15s-1d
      - 1h:30d
      - 1h:3w
      - 1h:3
      - 1h:3z
    aggregation: average
