logging:
    logdir: ""
    loglevel: "info"
cassandra:
    hosts:
        - "127.0.0.1"
        - "localhost"
    port: 9000
api:
    address: "0.0.0.0"
    port: 8080
elasticsearch:
    url: "http://127.0.0.1:9200"
    index: "cassabon"
carbon:
    address: "0.0.0.0"
    port: 2003
    protocol: "udp"
statsd:
    host: "localhost"
    port: 8125
rollups:
    default:
        - "10s:6h"
        - "1m:1d"
