# rpmrebuild autogenerated specfile
#SOURCERPM:    cassabon-1.0.0-1.src.rpm
#RPMVERSION:   4.8.0

BuildArch:     x86_64
Name:          cassabon
Version:       1.3.0
Release:       1
License:       MIT
Group:         Utilities
Summary:       Cassabon - Carbon Listener for Cassandra
URL:           https://github.com/jeffpierce/cassabon

Provides:      config(cassabon) = 1.3.0
Provides:      cassabon = 1.3.0
Provides:      cassabon(x86-64) = 1.3.0
Requires:      /bin/sh
Requires:      config(cassabon) = 1.3.0
%description

%files
%config %attr(0755, root, root) "/etc/init.d/cassabon"
%config %attr(0644, root, root) "/etc/logrotate.d/cassabon"
%config %attr(0644, root, root) "/etc/sysconfig/cassabon"
%attr(0750, root, cassabon) "/usr/local/bin/cassabon"
%dir %attr(2755, root, root) "/var/db/cassabon"
%attr(0644, root, root) "/var/db/cassabon/health"
%dir %attr(2775, root, cassabon) "/var/log/cassabon"
%pre -p /bin/sh
/usr/bin/getent passwd cassabon || /usr/sbin/useradd -r -d /usr/local/bin/cassabon -s /sbin/nologin cassabon
%changelog
* Wed Aug 17 2016 E. Edgeworth <also_no_spam_please@example.com> - 1.3.0
- new version of cassabon, specfile generated via rpmrebuild

* Wed Dec 09 2015 Jeff Pierce <no_spam_please@example.com> - 1.0.0-1
- Initial build.

